version: '3'

services:
  app:
    build:
      context: ./dockerfiles/nginx
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "8001:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: ./dockerfiles/php
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
  
  db:
    image: mariadb:11.7.2
    environment:
      - MARIADB_USER=symfony
      - MARIADB_DATABASE=symfony
      - MARIADB_PASSWORD=SecretDbPass
      - MARIADB_ROOT_PASSWORD=SecretDbPass
    ports:
      - "3307:3306"